version: '3.8'

services:
  get-service:
    build: ./get-service
    ports:
      - "3000:3000"
    env_file:
      - .env

  post-service:
    build: ./post-service
    ports:
      - "3001:3001"
    env_file:
      - .env

  put-service:
    build: ./put-service
    ports:
      - "3002:3002"
    env_file:
      - .env

  delete-service:
    build: ./delete-service
    ports:
      - "3003:3003"
    env_file:
      - .env
